<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;net6.0;net8.0</TargetFrameworks>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>

    <!-- NuGet Packaging -->
    <IsPackable>true</IsPackable>
    <PackageTags>rx</PackageTags>
    <Description>R3 &lt;-&gt; R3Async interop extensions</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/fedeAlterio/R3Async</RepositoryUrl>
    <Version>0.0.28</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageProjectUrl>https://github.com/fedeAlterio/R3Async</PackageProjectUrl>
    <Title>R3Async.R3Interop</Title>
    <Authors>fedefex</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="R3" Version="1.3.0" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework) == 'netstandard2.1'">
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\R3Async\R3Async.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Assets\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
