// This file is generated by a T4 template. It generates CombineLatest overloads for multiple sources.
// Run the T4 transformation to emit CombineLatest.cs

using System;
using System.Threading;
using System.Threading.Tasks;
using R3Async.Internals;

namespace R3Async;

public static partial class AsyncObservable
{
    // CombineLatest for 2 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        Func<T1, T2, TResult> selector)
    {
        return new CombineLatest2AsyncObservable<T1, T2, TResult>(src1, src2, selector);
    }

    sealed class CombineLatest2AsyncObservable<T1, T2, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, Func<T1, T2, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, Func<T1, T2, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;

            bool _done1;
            bool _done2;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2))
                {
                    return OnNextCombined(v1, v2, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2))
                {
                    return OnNextCombined(v1, v2, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 3 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        Func<T1, T2, T3, TResult> selector)
    {
        return new CombineLatest3AsyncObservable<T1, T2, T3, TResult>(src1, src2, src3, selector);
    }

    sealed class CombineLatest3AsyncObservable<T1, T2, T3, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, Func<T1, T2, T3, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, Func<T1, T2, T3, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3))
                {
                    return OnNextCombined(v1, v2, v3, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3))
                {
                    return OnNextCombined(v1, v2, v3, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3))
                {
                    return OnNextCombined(v1, v2, v3, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 4 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, T4, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        AsyncObservable<T4> src4,
        Func<T1, T2, T3, T4, TResult> selector)
    {
        return new CombineLatest4AsyncObservable<T1, T2, T3, T4, TResult>(src1, src2, src3, src4, selector);
    }

    sealed class CombineLatest4AsyncObservable<T1, T2, T3, T4, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, Func<T1, T2, T3, T4, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, src4, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, Func<T1, T2, T3, T4, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;
            IAsyncDisposable? _d4;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;
            Optional<T4> _val4 = Optional<T4>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            bool _done4;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
                _d4 = await src4.SubscribeAsync(OnNext_4, OnErrorResume, OnCompleted_4, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4))
                {
                    return OnNextCombined(v1, v2, v3, v4, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4))
                {
                    return OnNextCombined(v1, v2, v3, v4, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4))
                {
                    return OnNextCombined(v1, v2, v3, v4, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_4(T4 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val4 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4))
                {
                    return OnNextCombined(v1, v2, v3, v4, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_4(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done4 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, T4 v4, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3, v4);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }
                if (_d4 is not null)
                {
                    await _d4.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 5 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, T4, T5, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        AsyncObservable<T4> src4,
        AsyncObservable<T5> src5,
        Func<T1, T2, T3, T4, T5, TResult> selector)
    {
        return new CombineLatest5AsyncObservable<T1, T2, T3, T4, T5, TResult>(src1, src2, src3, src4, src5, selector);
    }

    sealed class CombineLatest5AsyncObservable<T1, T2, T3, T4, T5, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, Func<T1, T2, T3, T4, T5, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, src4, src5, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, Func<T1, T2, T3, T4, T5, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;
            IAsyncDisposable? _d4;
            IAsyncDisposable? _d5;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;
            Optional<T4> _val4 = Optional<T4>.Empty;
            Optional<T5> _val5 = Optional<T5>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            bool _done4;
            bool _done5;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
                _d4 = await src4.SubscribeAsync(OnNext_4, OnErrorResume, OnCompleted_4, cancellationToken);
                _d5 = await src5.SubscribeAsync(OnNext_5, OnErrorResume, OnCompleted_5, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_4(T4 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val4 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_4(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done4 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_5(T5 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val5 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_5(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done5 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3, v4, v5);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }
                if (_d4 is not null)
                {
                    await _d4.DisposeAsync();
                }
                if (_d5 is not null)
                {
                    await _d5.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 6 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, T4, T5, T6, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        AsyncObservable<T4> src4,
        AsyncObservable<T5> src5,
        AsyncObservable<T6> src6,
        Func<T1, T2, T3, T4, T5, T6, TResult> selector)
    {
        return new CombineLatest6AsyncObservable<T1, T2, T3, T4, T5, T6, TResult>(src1, src2, src3, src4, src5, src6, selector);
    }

    sealed class CombineLatest6AsyncObservable<T1, T2, T3, T4, T5, T6, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, Func<T1, T2, T3, T4, T5, T6, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, src4, src5, src6, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, Func<T1, T2, T3, T4, T5, T6, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;
            IAsyncDisposable? _d4;
            IAsyncDisposable? _d5;
            IAsyncDisposable? _d6;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;
            Optional<T4> _val4 = Optional<T4>.Empty;
            Optional<T5> _val5 = Optional<T5>.Empty;
            Optional<T6> _val6 = Optional<T6>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            bool _done4;
            bool _done5;
            bool _done6;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
                _d4 = await src4.SubscribeAsync(OnNext_4, OnErrorResume, OnCompleted_4, cancellationToken);
                _d5 = await src5.SubscribeAsync(OnNext_5, OnErrorResume, OnCompleted_5, cancellationToken);
                _d6 = await src6.SubscribeAsync(OnNext_6, OnErrorResume, OnCompleted_6, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_4(T4 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val4 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_4(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done4 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_5(T5 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val5 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_5(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done5 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_6(T6 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val6 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_6(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done6 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3, v4, v5, v6);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }
                if (_d4 is not null)
                {
                    await _d4.DisposeAsync();
                }
                if (_d5 is not null)
                {
                    await _d5.DisposeAsync();
                }
                if (_d6 is not null)
                {
                    await _d6.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 7 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, T4, T5, T6, T7, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        AsyncObservable<T4> src4,
        AsyncObservable<T5> src5,
        AsyncObservable<T6> src6,
        AsyncObservable<T7> src7,
        Func<T1, T2, T3, T4, T5, T6, T7, TResult> selector)
    {
        return new CombineLatest7AsyncObservable<T1, T2, T3, T4, T5, T6, T7, TResult>(src1, src2, src3, src4, src5, src6, src7, selector);
    }

    sealed class CombineLatest7AsyncObservable<T1, T2, T3, T4, T5, T6, T7, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, AsyncObservable<T7> src7, Func<T1, T2, T3, T4, T5, T6, T7, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, src4, src5, src6, src7, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, AsyncObservable<T7> src7, Func<T1, T2, T3, T4, T5, T6, T7, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;
            IAsyncDisposable? _d4;
            IAsyncDisposable? _d5;
            IAsyncDisposable? _d6;
            IAsyncDisposable? _d7;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;
            Optional<T4> _val4 = Optional<T4>.Empty;
            Optional<T5> _val5 = Optional<T5>.Empty;
            Optional<T6> _val6 = Optional<T6>.Empty;
            Optional<T7> _val7 = Optional<T7>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            bool _done4;
            bool _done5;
            bool _done6;
            bool _done7;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
                _d4 = await src4.SubscribeAsync(OnNext_4, OnErrorResume, OnCompleted_4, cancellationToken);
                _d5 = await src5.SubscribeAsync(OnNext_5, OnErrorResume, OnCompleted_5, cancellationToken);
                _d6 = await src6.SubscribeAsync(OnNext_6, OnErrorResume, OnCompleted_6, cancellationToken);
                _d7 = await src7.SubscribeAsync(OnNext_7, OnErrorResume, OnCompleted_7, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_4(T4 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val4 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_4(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done4 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_5(T5 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val5 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_5(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done5 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_6(T6 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val6 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_6(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done6 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_7(T7 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val7 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_7(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done7 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3, v4, v5, v6, v7);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }
                if (_d4 is not null)
                {
                    await _d4.DisposeAsync();
                }
                if (_d5 is not null)
                {
                    await _d5.DisposeAsync();
                }
                if (_d6 is not null)
                {
                    await _d6.DisposeAsync();
                }
                if (_d7 is not null)
                {
                    await _d7.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

    // CombineLatest for 8 sources
    public static AsyncObservable<TResult> CombineLatest<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(
        this AsyncObservable<T1> src1,
        AsyncObservable<T2> src2,
        AsyncObservable<T3> src3,
        AsyncObservable<T4> src4,
        AsyncObservable<T5> src5,
        AsyncObservable<T6> src6,
        AsyncObservable<T7> src7,
        AsyncObservable<T8> src8,
        Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> selector)
    {
        return new CombineLatest8AsyncObservable<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(src1, src2, src3, src4, src5, src6, src7, src8, selector);
    }

    sealed class CombineLatest8AsyncObservable<T1, T2, T3, T4, T5, T6, T7, T8, TResult>(AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, AsyncObservable<T7> src7, AsyncObservable<T8> src8, Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> selector) : AsyncObservable<TResult>
    {
        protected override async ValueTask<IAsyncDisposable> SubscribeAsyncCore(AsyncObserver<TResult> observer, CancellationToken cancellationToken)
        {
            var subscription = new CombineLatestSubscription(observer, src1, src2, src3, src4, src5, src6, src7, src8, selector);
            try
            {
                await subscription.SubscribeAsync(cancellationToken);
            }
            catch
            {
                await subscription.DisposeAsync();
                throw;
            }
            return subscription;
        }

        sealed class CombineLatestSubscription(AsyncObserver<TResult> observer, AsyncObservable<T1> src1, AsyncObservable<T2> src2, AsyncObservable<T3> src3, AsyncObservable<T4> src4, AsyncObservable<T5> src5, AsyncObservable<T6> src6, AsyncObservable<T7> src7, AsyncObservable<T8> src8, Func<T1, T2, T3, T4, T5, T6, T7, T8, TResult> selector) : IAsyncDisposable
        {
            readonly AsyncGate _gate = new();
            readonly CancellationTokenSource _disposeCts = new();
            IAsyncDisposable? _d1;
            IAsyncDisposable? _d2;
            IAsyncDisposable? _d3;
            IAsyncDisposable? _d4;
            IAsyncDisposable? _d5;
            IAsyncDisposable? _d6;
            IAsyncDisposable? _d7;
            IAsyncDisposable? _d8;

            Optional<T1> _val1 = Optional<T1>.Empty;
            Optional<T2> _val2 = Optional<T2>.Empty;
            Optional<T3> _val3 = Optional<T3>.Empty;
            Optional<T4> _val4 = Optional<T4>.Empty;
            Optional<T5> _val5 = Optional<T5>.Empty;
            Optional<T6> _val6 = Optional<T6>.Empty;
            Optional<T7> _val7 = Optional<T7>.Empty;
            Optional<T8> _val8 = Optional<T8>.Empty;

            bool _done1;
            bool _done2;
            bool _done3;
            bool _done4;
            bool _done5;
            bool _done6;
            bool _done7;
            bool _done8;
            int _disposed;

            public async ValueTask SubscribeAsync(CancellationToken cancellationToken)
            {
                _d1 = await src1.SubscribeAsync(OnNext_1, OnErrorResume, OnCompleted_1, cancellationToken);
                _d2 = await src2.SubscribeAsync(OnNext_2, OnErrorResume, OnCompleted_2, cancellationToken);
                _d3 = await src3.SubscribeAsync(OnNext_3, OnErrorResume, OnCompleted_3, cancellationToken);
                _d4 = await src4.SubscribeAsync(OnNext_4, OnErrorResume, OnCompleted_4, cancellationToken);
                _d5 = await src5.SubscribeAsync(OnNext_5, OnErrorResume, OnCompleted_5, cancellationToken);
                _d6 = await src6.SubscribeAsync(OnNext_6, OnErrorResume, OnCompleted_6, cancellationToken);
                _d7 = await src7.SubscribeAsync(OnNext_7, OnErrorResume, OnCompleted_7, cancellationToken);
                _d8 = await src8.SubscribeAsync(OnNext_8, OnErrorResume, OnCompleted_8, cancellationToken);
            }

            ValueTask OnNext_1(T1 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val1 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_1(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done1 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_2(T2 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val2 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_2(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done2 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_3(T3 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val3 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_3(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done3 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_4(T4 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val4 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_4(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done4 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_5(T5 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val5 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_5(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done5 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_6(T6 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val6 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_6(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done6 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_7(T7 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val7 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_7(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done7 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }

            ValueTask OnNext_8(T8 value, CancellationToken cancellationToken)
            {
                lock (_disposeCts)
                {
                    _val8 = new(value);
                }

                if (_val1.TryGetValue(out var v1) && _val2.TryGetValue(out var v2) && _val3.TryGetValue(out var v3) && _val4.TryGetValue(out var v4) && _val5.TryGetValue(out var v5) && _val6.TryGetValue(out var v6) && _val7.TryGetValue(out var v7) && _val8.TryGetValue(out var v8))
                {
                    return OnNextCombined(v1, v2, v3, v4, v5, v6, v7, v8, cancellationToken);
                }
                return default;
            }

            ValueTask OnCompleted_8(Result result)
            {
                if (result.IsFailure)
                {
                    return CompleteAsync(result);
                }

                bool shouldComplete;
                lock (_disposeCts)
                {
                    _done8 = true;
                    shouldComplete = _done1 && _done2 && _done3 && _done4 && _done5 && _done6 && _done7 && _done8;
                }

                return shouldComplete ? observer.OnCompletedAsync(result) : default;
            }


            async ValueTask OnNextCombined(T1 v1, T2 v2, T3 v3, T4 v4, T5 v5, T6 v6, T7 v7, T8 v8, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    var v = selector(v1, v2, v3, v4, v5, v6, v7, v8);
                    await observer.OnNextAsync(v, linkedCts.Token);
                }
            }

            async ValueTask OnErrorResume(Exception error, CancellationToken cancellationToken)
            {
                if (_disposed == 1) return;
                using var linkedCts = CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, _disposeCts.Token);
                using (await _gate.LockAsync())
                {
                    await observer.OnErrorResumeAsync(error, linkedCts.Token);
                }
            }

            async ValueTask CompleteAsync(Result? result)
            {
                if (Interlocked.Exchange(ref _disposed, 1) == 1) return;

                _disposeCts.Cancel();

                if (_d1 is not null)
                {
                    await _d1.DisposeAsync();
                }
                if (_d2 is not null)
                {
                    await _d2.DisposeAsync();
                }
                if (_d3 is not null)
                {
                    await _d3.DisposeAsync();
                }
                if (_d4 is not null)
                {
                    await _d4.DisposeAsync();
                }
                if (_d5 is not null)
                {
                    await _d5.DisposeAsync();
                }
                if (_d6 is not null)
                {
                    await _d6.DisposeAsync();
                }
                if (_d7 is not null)
                {
                    await _d7.DisposeAsync();
                }
                if (_d8 is not null)
                {
                    await _d8.DisposeAsync();
                }

                if (result is not null)
                {
                    await observer.OnCompletedAsync(result.Value);
                }

                _disposeCts.Dispose();
            }

            public ValueTask DisposeAsync() => CompleteAsync(null);
        }
    }

}

